name: build_apk

# action事件触发
on:
    push:
        tags:
            - v*

# 可以有多个jobs
jobs:
    build_apk:
        # 运行环境 ubuntu-latest window-latest mac-latest
        runs-on: ubuntu-latest
        permissions:
          contents: write

        steps:
            - name: 代码迁出
              uses: actions/checkout@v4

            - name: 构建Java环境
              uses: actions/setup-java@v4
              with:
                  distribution: "zulu"
                  java-version: "17"

            - name: 检查缓存
              uses: actions/cache@v4
              id: cache-flutter
              with:
                  path: /root/flutter-sdk # Flutter SDK 的路径
                  key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

            - name: 安装Flutter
              if: steps.cache-flutter.outputs.cache-hit != 'true'
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: 3.32.7
                  channel: any

            - name: 下载项目依赖
              run: flutter pub get

            - name: 解码生成 key.properties
              run: echo "$KEY_PROPERTIES" | base64 -di > android/key.properties
              env:
                KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

            - name: 解码生成 jks
              run: echo $KEYSTORE_BASE64 | base64 -di > android/app/release.jks
              env:
                  KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

            - name: flutter build apk
              run: flutter build apk --release --split-per-abi

            - name: 发布
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "build/app/outputs/flutter-apk/app-*.apk"
                  allowUpdates: true